/**
 * Utilities for dynamically generating Hunspell .dic and .aff files
 * from Easper lexicon entries.
 *
 * Per requirements:
 * The "Headword" field is mandatory in all lexicons, and the Hunspell dictionary
 * is built exclusively from the "Headword" column.
 */

import { getEntryFieldValue } from './lexiconTsv.js';

/**
 * Creates default Hunspell .aff affix content configured for UTF-8.
 * @param {Object} [options]
 * @param {string} [options.languageVariety] - Optional language code/variety name
 * @param {string} [options.wordchars] - Extra characters treated as word parts (e.g. hyphens, apostrophes)
 * @returns {string}
 */
export function createDefaultAffContent(options = {}) {
  const wordchars = options.wordchars || "-'’";
  const lines = [
    '# Generated by Easper Web Hunspell Engine',
    'SET UTF-8',
    'FLAG UTF-8',
    `WORDCHARS ${wordchars}`,
    'TRY esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ',
    '',
  ];
  return lines.join('\n');
}

/**
 * Extracts normalized word tokens from an entry string or phrase.
 * Strips boundary punctuation while preserving internal apostrophes/hyphens and Unicode letters.
 * @param {string} text
 * @returns {string[]}
 */
export function extractWordsFromText(text) {
  if (!text || typeof text !== 'string') return [];
  const trimmed = text.trim();
  if (!trimmed) return [];

  // Split by whitespace
  const parts = trimmed.split(/\s+/);
  const words = [];

  for (const part of parts) {
    // Strip leading and trailing punctuation (e.g. quotes, brackets, dots, commas, question marks)
    const cleaned = part.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, '').trim();
    if (cleaned.length > 0) {
      words.push(cleaned);
    }
  }

  return words;
}

/**
 * Dynamically builds a standard Hunspell .dic string from a lexicon.
 * Uses ONLY the mandatory "Headword" field.
 * 
 * Format:
 * Line 1: Word count
 * Line 2..N: Word
 *
 * @param {Object} lexicon - Easper lexicon object with { fields, entries, languageVariety }
 * @param {Object} [options]
 * @param {boolean} [options.tokenizePhrases=true] - If true, multi-word headwords are split into individual word tokens.
 * @returns {{ dicContent: string, words: string[], wordCount: number, affContent: string, resolvedFieldId: string|null, resolvedFieldName: string }}
 */
export function buildHunspellDict(lexicon, options = {}) {
  if (!lexicon) {
    return {
      dicContent: '0\n',
      words: [],
      wordCount: 0,
      affContent: createDefaultAffContent(),
      resolvedFieldId: null,
      resolvedFieldName: 'Headword',
    };
  }

  const fields = lexicon.fields || [];
  const entries = lexicon.entries || [];

  if (entries.length === 0 || fields.length === 0) {
    return {
      dicContent: '0\n',
      words: [],
      wordCount: 0,
      affContent: createDefaultAffContent({ languageVariety: lexicon.languageVariety }),
      resolvedFieldId: null,
      resolvedFieldName: 'Headword',
    };
  }

  // Find the mandatory Headword field
  let headwordField = fields.find(
    (f) => (f.name || '').trim().toLowerCase() === 'headword'
  );

  // Fallback to first field if headword was absent
  if (!headwordField && fields.length > 0) {
    headwordField = fields[0];
  }

  const tokenizePhrases = options.tokenizePhrases !== false;
  const wordSet = new Set();

  function addValToSet(rawVal) {
    if (!rawVal || typeof rawVal !== 'string') return;
    const trimmed = rawVal.trim();
    if (!trimmed) return;

    if (!/\s/.test(trimmed)) {
      const cleaned = trimmed.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, '').trim();
      if (cleaned) {
        wordSet.add(cleaned);
      }
    } else if (tokenizePhrases) {
      const tokens = extractWordsFromText(trimmed);
      for (const token of tokens) {
        if (token) wordSet.add(token);
      }
    }
  }

  // Extract exclusively from the Headword column
  if (headwordField) {
    for (const entry of entries) {
      addValToSet(getEntryFieldValue(entry, headwordField));
    }
  }

  // Sort words alphabetically with numeric sensitivity
  const words = Array.from(wordSet).sort((a, b) =>
    a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' })
  );

  const lines = [words.length.toString(), ...words];
  const dicContent = lines.join('\n') + '\n';
  const affContent = createDefaultAffContent({ languageVariety: lexicon.languageVariety });

  return {
    dicContent,
    words,
    wordCount: words.length,
    affContent,
    resolvedFieldId: headwordField?.id || null,
    resolvedFieldName: 'Headword',
  };
}
